/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package noughtsandcrossesdemo;

import java.awt.Color;
import java.awt.Font;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author mortimer
 */
public class GameForm extends javax.swing.JFrame {
    JLabel[][]board=new JLabel[3][3];
    static boolean isAgainstComp;
    static boolean easyComp;
    static boolean alphaBetaPrune;
    /**
     * Creates new form GameUI
     */
    boolean playerOneIsComp;
    TicTacToe game;
    public GameForm(boolean isAgainstComputer,boolean isEasy, boolean enablePrune) {
        easyComp=isEasy;
        alphaBetaPrune = enablePrune;
        playerOneIsComp=(Math.random()>0.5);
        isAgainstComp=isAgainstComputer;
        game = new TicTacToe(alphaBetaPrune);
        initComponents();
        if(playerOneIsComp && isAgainstComputer) playerInfoLbl.setText("You are playing as noughts");
        else playerInfoLbl.setText("You are playing as crosses");
        if(!isAgainstComp) playerInfoLbl.setText("Player One is playing as crosses");
        playerInfoLbl.setEnabled(true);
        playerInfoLbl.setVisible(true);
        int width=150;
        int height =150;
        int yLoc=10;
        int startingX=10;
        int xLoc=startingX;
        board[0][0]=lbl00;board[0][1]=lbl01;board[0][2]=lbl02;
        board[1][0]=lbl10;board[1][1]=lbl11;board[1][2]=lbl12;
        board[2][0]=lbl20;board[2][1]=lbl21;board[2][2]=lbl22;
        for(int y=0;y<board.length;y++){
            for(int x =0;x<board[0].length;x++){
                jPanel1.remove(board[2-y][x]);
                board[2-y][x].setSize(width, height);
                board[2-y][x].setLocation(xLoc, yLoc);
                board[2-y][x].setBorder(new LineBorder(Color.black));
                board[2-y][x].setBounds(xLoc, yLoc, width, height);
                Font font = new Font("f", board[2-y][x].getFont().getStyle(), board[2-y][x].getFont().getSize()*16);
                board[2-y][x].setFont(font);
                board[2-y][x].setText("");
                jPanel1.add(board[2-y][x]);
                xLoc=xLoc+width;
            }
            xLoc=startingX;
            yLoc=yLoc+height;
        }
        if(playerOneIsComp==true&&isAgainstComputer==true){
            addComputerMove(!isEasy);
        }
    }
    private void addComputerMove(boolean isHard){
        if(isHard==false){
            game.makeRandomMove();
        }else{
            game.makeBestMove();
            updateStatesLbl();
        }
        updateUI();
        handleGameState();
    }
    public void updateStatesLbl(){
         statesExploredLbl.setVisible(true);
         statesExploredLbl.setEnabled(true);
         statesExploredLbl.setText("States Explored by Computer: "+String.valueOf(game.statesExplored));
    }
    public void updateUI(){
        for(int y = 0; y < 3; y++){
            for(int x = 0; x < 3; x++){
                if (game.GRID[y][x] == TicTacToe.CROSS_VAL) {
                    board[y][x].setText("X");
                } else if (game.GRID[y][x] == TicTacToe.NOUGHT_VAL) {
                    board[y][x].setText("0");
                }
            }
        }
    }
    
    private void handleGameState(){
        if(game.gameState==TicTacToe.NOUGHT_VAL){
            JOptionPane.showMessageDialog(this, "Noughts Win!", "Game Over", JOptionPane.OK_OPTION);
            MenuUI menu = new MenuUI();
            menu.setVisible(true);
            this.dispose();
        }else if(game.gameState == TicTacToe.CROSS_VAL){
            JOptionPane.showMessageDialog(this, "Crosses Win!", "Game Over", JOptionPane.OK_OPTION);
            MenuUI menu = new MenuUI();
            menu.setVisible(true);
            this.dispose();
        }else if(game.gameState==TicTacToe.EMPTY_VAL){
            JOptionPane.showMessageDialog(this, "It's a draw!", "Game Over", JOptionPane.OK_OPTION);
            MenuUI menu = new MenuUI();
            menu.setVisible(true);
            this.dispose();
        }else{
            if(isAgainstComp){
                if((playerOneIsComp && (game.moveNo % 2 == 0)) || (!playerOneIsComp && (game.moveNo % 2 == 1))){
                    addComputerMove(!easyComp);
                }
            }
        }
    }
    private void addMove(int[]yThenX){
        game.addMove(yThenX[1], yThenX[0]);
        updateUI();
        handleGameState();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuBtn = new javax.swing.JButton();
        lbl00 = new javax.swing.JLabel();
        lbl01 = new javax.swing.JLabel();
        lbl02 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        lbl12 = new javax.swing.JLabel();
        lbl20 = new javax.swing.JLabel();
        lbl21 = new javax.swing.JLabel();
        lbl22 = new javax.swing.JLabel();
        playerInfoLbl = new javax.swing.JLabel();
        statesExploredLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuBtn.setText("Menu");
        menuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBtnActionPerformed(evt);
            }
        });

        lbl00.setText("jLabel1");
        lbl00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl00MouseClicked(evt);
            }
        });

        lbl01.setText("jLabel2");
        lbl01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl01MouseClicked(evt);
            }
        });

        lbl02.setText("jLabel3");
        lbl02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl02MouseClicked(evt);
            }
        });

        lbl10.setText("jLabel4");
        lbl10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl10MouseClicked(evt);
            }
        });

        lbl11.setText("jLabel5");
        lbl11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl11MouseClicked(evt);
            }
        });

        lbl12.setText("jLabel6");
        lbl12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl12MouseClicked(evt);
            }
        });

        lbl20.setText("jLabel7");
        lbl20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl20MouseClicked(evt);
            }
        });

        lbl21.setText("jLabel8");
        lbl21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl21MouseClicked(evt);
            }
        });

        lbl22.setText("jLabel9");
        lbl22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl22MouseClicked(evt);
            }
        });

        playerInfoLbl.setText("Player info");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lbl00)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl20)
                .addGap(125, 125, 125))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl12)
                    .addComponent(lbl11)
                    .addComponent(lbl10))
                .addGap(33, 33, 33)
                .addComponent(lbl21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 543, Short.MAX_VALUE)
                .addComponent(lbl02)
                .addGap(83, 83, 83))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl01)
                        .addGap(157, 157, 157))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl22)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(statesExploredLbl)
                            .addComponent(menuBtn))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(playerInfoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerInfoLbl)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl00)
                    .addComponent(lbl20))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbl01)
                        .addGap(15, 15, 15)
                        .addComponent(lbl12)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl02)
                            .addComponent(lbl10)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lbl21)))
                .addGap(18, 18, 18)
                .addComponent(lbl22)
                .addGap(32, 32, 32)
                .addComponent(statesExploredLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addComponent(lbl11)
                .addGap(18, 18, 18)
                .addComponent(menuBtn)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBtnActionPerformed
        MenuUI menu = new MenuUI();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuBtnActionPerformed

    private void lbl21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl21MouseClicked
        int []yThenX={2,1};
        if(game.GRID[yThenX[0]][yThenX[1]]==TicTacToe.EMPTY_VAL){
            addMove(yThenX);
        }
    }//GEN-LAST:event_lbl21MouseClicked

    private void lbl00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl00MouseClicked
        // TODO add your handling code here:
                int []yThenX={0,0};
        if(game.GRID[yThenX[0]][yThenX[1]]==TicTacToe.EMPTY_VAL){
            addMove(yThenX);
        }
    }//GEN-LAST:event_lbl00MouseClicked

    private void lbl20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl20MouseClicked
        // TODO add your handling code here:        
        int []yThenX={2,0};
        if(game.GRID[yThenX[0]][yThenX[1]]==TicTacToe.EMPTY_VAL){
            addMove(yThenX);
        }
    }//GEN-LAST:event_lbl20MouseClicked

    private void lbl12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl12MouseClicked
        // TODO add your handling code here:
                int []yThenX={1,2};
        if(game.GRID[yThenX[0]][yThenX[1]]==TicTacToe.EMPTY_VAL){
            addMove(yThenX);
        }
    }//GEN-LAST:event_lbl12MouseClicked

    private void lbl01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl01MouseClicked
        // TODO add your handling code here:
                int []yThenX={0,1};
        if(game.GRID[yThenX[0]][yThenX[1]]==TicTacToe.EMPTY_VAL){
            addMove(yThenX);
        }
    }//GEN-LAST:event_lbl01MouseClicked

    private void lbl02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl02MouseClicked
        // TODO add your handling code here:
                int []yThenX={0,2};
        if(game.GRID[yThenX[0]][yThenX[1]]==TicTacToe.EMPTY_VAL){
            addMove(yThenX);
        }
    }//GEN-LAST:event_lbl02MouseClicked

    private void lbl10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl10MouseClicked
        // TODO add your handling code here:
                int []yThenX={1,0};
        if(game.GRID[yThenX[0]][yThenX[1]]==TicTacToe.EMPTY_VAL){
            addMove(yThenX);
        }
    }//GEN-LAST:event_lbl10MouseClicked

    private void lbl22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl22MouseClicked
        // TODO add your handling code here:
                int []yThenX={2,2};
        if(game.GRID[yThenX[0]][yThenX[1]]==TicTacToe.EMPTY_VAL){
            addMove(yThenX);
        }
    }//GEN-LAST:event_lbl22MouseClicked

    private void lbl11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl11MouseClicked
        // TODO add your handling code here:
                int []yThenX={1,1};
        if(game.GRID[yThenX[0]][yThenX[1]]==TicTacToe.EMPTY_VAL){
            addMove(yThenX);
        }
    }//GEN-LAST:event_lbl11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameForm(isAgainstComp,easyComp, alphaBetaPrune).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl00;
    private javax.swing.JLabel lbl01;
    private javax.swing.JLabel lbl02;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl20;
    private javax.swing.JLabel lbl21;
    private javax.swing.JLabel lbl22;
    private javax.swing.JButton menuBtn;
    private javax.swing.JLabel playerInfoLbl;
    private javax.swing.JLabel statesExploredLbl;
    // End of variables declaration//GEN-END:variables
}
